apiVersion: v1
kind: Service
metadata:
  labels:
    app: futurice-calc-depl
  name: futurice-calc-svc
  namespace: futurice
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: futurice-calc-depl
  type: LoadBalancer